# TEMPLATE — do NOT commit this filled in as plaintext.
#
# 1. Copy to cloud-credentials.enc.yaml
# 2. Paste the values from Terraform:
#      terraform -chdir=infra output -raw velero_s3_access_key_id
#      terraform -chdir=infra output -raw velero_s3_secret_key
# 3. Encrypt in place:
#      sops --encrypt --in-place k8s/backup/cloud-credentials.enc.yaml
# 4. Commit the encrypted file.
apiVersion: v1
kind: Secret
metadata:
    name: velero-cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:5GjCRGgm20SIjmRX4sPPwIAsYvZhyEWP1wy1HiB7tHzo/BikWafKSyMu78cY52Xe42YmcBLOavUwZvXvewH8j3eAbeWByQxBeCGGqsm5dL3+cNR5+Mys3YfJ+CguuLmGJY1Ztnnh56wB8GqK07amsG6QEsT1eMri+dQnZHUfMg==,iv:J2ChNEMoxhYhYgDD8kAn+3tIYoTyrHDr6LQtqUDIctA=,tag:KQp3MsEWotAyqoo8Ned//Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146qdcn0v66z6mylvdrnucy5g3zencx8wqlga78jd2zwvzknklctqkgpdkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3JvdnhuWjRYSkhYMXZY
            KzB5ZlJsUkduWDhnalVxNWdUOGRpV2duWGpZCm8weW9LODFmQytJbnBnRXJGU1Az
            L3M4cnZQb3lET1ZkbWJxdWVNSSs3WTAKLS0tICtPbVZaczJESDJmRjgvSWJTLzEv
            YVd0ZDkxZ2hUMDhKcnpybGFUV3lqUDAKEHATR912KJI/wzZpPGbsOkJ+07MueyG0
            sGnXsL3I7wtsO0fvhuf/QQ83q3jGtBfTANysfpW1nggNXITwmLZlEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T18:58:21Z"
    mac: ENC[AES256_GCM,data:pyX/8Xng5gg5bR98oxn1RxyAYrsNYOOBekYeilyF04IME8X5q9cgRdRTef6KHSOtVo7s4riDYb+4WSlgaPeyzmF5wPzxdLzwAmBwfFcWDZQ8OVyy8iVU+oZdv2KGCFVXKLzMwMGyqx4+AQGxAwsio877ADA4ab6gn9L/RQVXtYU=,iv:A4gC6tp6JZg2u4Tj8i97Ne+FHIf8K9iAODPMlzTJ828=,tag:p2BY7NCxiO2+ojT9JW+ACg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
