# TEMPLATE — do NOT commit this filled in as plaintext.
#
# 1. Copy to cloud-credentials.enc.yaml
# 2. Paste the values from Terraform:
#      terraform -chdir=infra output -raw velero_s3_access_key_id
#      terraform -chdir=infra output -raw velero_s3_secret_key
# 3. Encrypt in place:
#      sops --encrypt --in-place k8s/backup/cloud-credentials.enc.yaml
# 4. Commit the encrypted file.
apiVersion: v1
kind: Secret
metadata:
    name: velero-cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:a3SCtXVBjRzHOA5nCcmEUeDUXQPi1IB/o8/JGg5XOfFRyx09cTrIbfiVTCnEYkPQlzosixLGhyYsCII9cYL2arF3801VTlc/VXEbzTybLYIUuyQ965qFM3hPfF6MuFf2DcFWfFvq+HvOIW3XmzglHF0ewKmXHewvgYJw5HAB0HxLuKiHC2L+9w==,iv:QtqF9QQ25ExNrD2Yj96mGyuWyfd2vbX32aCQgQekPO4=,tag:7QaQLDSZRUKz0GsWkNhsAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146qdcn0v66z6mylvdrnucy5g3zencx8wqlga78jd2zwvzknklctqkgpdkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZUg0LzZtZEtFQk10ckdj
            SUx0MCtLZkNnMktEaldnZEZDc2l0MmtpMXlFCnp0M2FCdHRZbXhBTVJrZnF5bENM
            Q285eFFYVGFuT1UzYUVYeUJwRzdnT0kKLS0tIHRHNjhmd1VFM1lHT2xNT3hGS2xm
            Q0UwNUtKRWtVbHZWV1RVcGdwQ0RhY00KCkMXQQW+GYL4TztZXGOurjvFMTZUEEFg
            hx0THh/xkNyNHjzdFq90aVMtwz7veZNFG37gOchDD2ETWTRPvbGOSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T19:54:01Z"
    mac: ENC[AES256_GCM,data:EzzsrpkabU9Wm8v6QUjHzelE6imd+5DZSXBMiXEz235KwI7/trhMMwz9fmtXMcjNY3iy/N8dt+F6FJD8QPjvnfWZtpQ8jocyn1hrh5tEoowUCegbNzg9zszsexx1FFDm3DRc150UIemsg9lcI/aCNLp8mG2WnI28S9A3y4sOArc=,iv:XQf9utHHW88oUAhE5mdlU96hnuJOKmBUUuqfCggxiA8=,tag:4CuRfJK+XRR/FxN2MUZEEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
